name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - fix-before-prisma3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/dev/mapEvents
            git pull
            docker compose down -v
            docker compose build --no-cache
            docker compose up -d